openapi: 3.0.1
info:
  title: Consumer API
  description: Welcome to ChargeAfter API reference! This API is implemented in a RESTful state of mind, it has straight-forward,
    resource-oriented endpoints, and produces standard HTTP response codes to communicate back the result of operations. To
    get started please contact ChargeAfter support to get your API keys, and get an access to your testing and live environments.
  termsOfService: https://chargeafter.com/privacy-policy
  contact:
    name: Customer Support
    email: support@chargeafter.com
  version: 2.2.9+f98ebe1eff64a212ae2a437793a1a4ac280664bb
servers:
- url: https://api-sandbox.ca-dev.co
  description: Local Environment
- url: https://api.chargeafter.com
  description: Production Environment
security:
- apiKey: []
paths:
  /v2/consumers/{consumerId}:
    get:
      tags:
      - ConsumersV2
      summary: Get consumer details
      description: Returns consumer details
      parameters:
      - name: consumerId
        in: path
        description: Unique identifier of the consumer
        required: true
        schema:
          type: string
      - name: channel
        in: query
        description: "Optional Channel. If not provided, the E_COMMERCE channel will be used.<br />\r\nOther options are IN_STORE\
          \ / CALL_CENTER / IN_HOME"
        schema:
          type: string
      - name: storeId
        in: query
        description: The store identifier
        schema:
          type: string
      - name: posId
        in: query
        description: The point of sale identifier
        schema:
          type: string
      - name: posType
        in: query
        description: The point of sale type
        schema:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.PosType'
      - name: currency
        in: query
        description: Optional ISO 4217 currency code. If not provided, the USD currency will be used.
        schema:
          type: string
      responses:
        '200':
          description: Consumer is found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerResponse'
        '400':
          description: Bad Request Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    example: Unique RequestId
                  message:
                    type: string
                    example: Message Describing The Error
        '401':
          description: Unauthorized
        '404':
          description: Consumer is not found or the user is unauthorized to request
          content:
            application/json:
              schema:
                example:
                  errorCode: '0'
                  code: '400'
                  message: Consumer is not found
        '422':
          description: Input Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        field:
                          type: string
                        validationState:
                          type: string
                        error:
                          type: string
                example:
                  RequestId: Unique RequestId
                  Message: Input Validation Failure
                  Errors:
                  - Field: RequestField1
                    ValidationState: Invalid
                    Error: RequestField1 should be up to 150 characters, and can contain a-z, A-Z, _ characters.
        '500':
          description: General Server Error
          content:
            application/json:
              schema:
                example:
                  requestId: Unique RequestId
                  errors:
                  - code: '1'
                    description: Internal unknown error occurred
  /v2/consumers/{consumerId}/accounts:
    get:
      tags:
      - ConsumersV2
      summary: Get accounts by consumerId
      description: Lookup existing accounts by consumerId
      parameters:
      - name: consumerId
        in: path
        description: Unique identifier of the consumer
        required: true
        schema:
          type: string
      - name: channel
        in: query
        description: "Optional Channel. If not provided, the E_COMMERCE channel will be used.<br />\r\nOther options are IN_STORE\
          \ / CALL_CENTER / IN_HOME"
        schema:
          type: string
      - name: storeId
        in: query
        description: The store identifier
        schema:
          type: string
      - name: posId
        in: query
        description: The point of sale identifier
        schema:
          type: string
      - name: posType
        in: query
        description: The point of sale type
        schema:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.PosType'
      - name: currency
        in: query
        description: Optional ISO 4217 currency code. If not provided, the USD currency will be used.
        schema:
          type: string
      responses:
        '200':
          description: Request is successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.LookupAccountsResponse'
        '400':
          description: Bad Request Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                    example: Unique RequestId
                  message:
                    type: string
                    example: Message Describing The Error
        '401':
          description: Unauthorized
        '404':
          description: Consumer is not found or the user is unauthorized to request
          content:
            application/json:
              schema:
                example:
                  errorCode: '0'
                  code: '400'
                  message: Consumer is not found
        '422':
          description: Server unable to process request because it contains invalid data
          content:
            application/json:
              schema:
                type: object
                properties:
                  requestId:
                    type: string
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      properties:
                        field:
                          type: string
                        validationState:
                          type: string
                        error:
                          type: string
                example:
                  RequestId: Unique RequestId
                  Message: Input Validation Failure
                  Errors:
                  - Field: RequestField1
                    ValidationState: Invalid
                    Error: RequestField1 should be up to 150 characters, and can contain a-z, A-Z, _ characters.
        '500':
          description: General Server Error
          content:
            application/json:
              schema:
                example:
                  requestId: Unique RequestId
                  errors:
                  - code: '1'
                    description: Internal unknown error occurred
components:
  schemas:
    ChargeAfter.BFF.Domain.Entities.Discount:
      type: object
      properties:
        name:
          type: string
          nullable: true
        amount:
          type: number
          format: double
      additionalProperties: false
    ChargeAfter.BFF.Domain.Entities.Item:
      type: object
      properties:
        name:
          type: string
          nullable: true
        price:
          type: number
          format: double
        sku:
          type: string
          nullable: true
        quantity:
          type: integer
          format: int32
        leasable:
          type: boolean
          nullable: true
        productCategory:
          type: string
          nullable: true
        warranty:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.BFF.Domain.Entities.Warranty'
          nullable: true
      additionalProperties: false
    ChargeAfter.BFF.Domain.Entities.Warranty:
      type: object
      properties:
        name:
          type: string
          nullable: true
        sku:
          type: string
          nullable: true
        price:
          type: number
          format: double
      additionalProperties: false
    ChargeAfter.ConsumersV1.Domain.NoConsumerAccountsException:
      type: object
      properties:
        context:
          nullable: true
          readOnly: true
          deprecated: true
        message:
          type: string
          nullable: true
        data:
          type: object
          additionalProperties: {}
          nullable: true
          readOnly: true
        innerException:
          nullable: true
        helpLink:
          type: string
          nullable: true
        source:
          type: string
          nullable: true
        hResult:
          type: integer
          format: int32
        stackTrace:
          type: string
          nullable: true
          readOnly: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Models.AccountInfo:
      required:
      - account
      type: object
      properties:
        account:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Account'
          description: Consumer account as returned by the configured lender
        accountToken:
          type: string
          description: Account token used for confirmation/charge creation. Returned for approved account
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Requests.CreateChargeRequestBody:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.BFF.Domain.Entities.Item'
          nullable: true
        discounts:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.BFF.Domain.Entities.Discount'
          nullable: true
        taxAmount:
          type: number
          format: double
        shippingAmount:
          type: number
          format: double
        totalAmount:
          type: number
          format: double
        lenderId:
          type: string
          nullable: true
        merchantOrderId:
          type: string
          nullable: true
        promoCode:
          type: string
          nullable: true
        storeId:
          type: string
          nullable: true
        channel:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.Channel'
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AdditionalIds:
      type: object
      properties:
        socialInsuranceNumber:
          type: string
          nullable: true
          example: '454654654'
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Address:
      type: object
      properties:
        city:
          type: string
          nullable: true
          example: Springfield
        line1:
          type: string
          nullable: true
          example: 273 Lee Avenue
        line2:
          type: string
          nullable: true
        state:
          type: string
          nullable: true
          example: MA
        zipCode:
          type: string
          nullable: true
          example: '01104'
        country:
          type: string
          nullable: true
          example: US
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCredit:
      type: object
      properties:
        creditAmount:
          type: number
          format: double
        lender:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Lender'
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCreditExtended:
      type: object
      properties:
        lender:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCreditLender'
          nullable: true
        creditAmount:
          type: number
          format: double
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCreditLender:
      type: object
      properties:
        isUpsaleEnabled:
          type: boolean
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCreditResponse:
      type: object
      properties:
        availableCredit:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCreditExtended'
          nullable: true
        prequalifyConfirmationToken:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerAccount:
      type: object
      properties:
        lenderId:
          type: string
          description: Lender id
          nullable: true
        lenderName:
          type: string
          description: Lender name
          nullable: true
        creditInfo:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.CreditInfo'
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerApplication:
      type: object
      properties:
        consumerId:
          type: string
          nullable: true
        accountToken:
          type: string
          nullable: true
        applicationId:
          type: string
          nullable: true
        lenderId:
          type: string
          nullable: true
        updated:
          type: string
          format: date-time
        status:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.ConsumerApplicationStatus'
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerApplicationsResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerApplication'
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.ConsumerResponse:
      type: object
      properties:
        id:
          type: string
          description: Unique consumer id
          nullable: true
          example: 63126524b97bd7d254c71041
        firstName:
          type: string
          nullable: true
          example: John
        lastName:
          type: string
          nullable: true
          example: Arlen
        email:
          type: string
          nullable: true
          example: someone@example.com
        shippingAddress:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Address'
          nullable: true
        billingAddress:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Address'
          nullable: true
        netMonthlyIncome:
          type: number
          format: double
          nullable: true
          example: 5000
        grossMonthlyIncome:
          type: number
          format: double
          nullable: true
        dateOfBirth:
          type: string
          format: date-time
          nullable: true
        socialSecurityNumber:
          type: string
          nullable: true
          example: '324620074'
        additionalIds:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AdditionalIds'
          nullable: true
        mobilePhoneNumber:
          type: string
          nullable: true
        housingStatus:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.ResidenceType'
          nullable: true
        merchantConsumerId:
          type: string
          nullable: true
          example: 624d519bde8287d9542d4484
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.CreateChargeResponse:
      type: object
      properties:
        buyerId:
          type: string
          nullable: true
        buyerType:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Contracts.BuyerType'
        channel:
          type: string
          nullable: true
        consumerId:
          type: string
          nullable: true
        id:
          type: string
          nullable: true
        lender:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Lender'
          nullable: true
        merchantOrderId:
          type: string
          nullable: true
        paymentPlan:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.PaymentPlan'
          nullable: true
        refundedAmount:
          type: number
          format: double
        state:
          type: string
          nullable: true
        totalAmount:
          type: number
          format: double
        updatedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.CreditInfo:
      type: object
      properties:
        availableAmount:
          type: number
          description: Available credit amount
          format: double
          example: 2780.25
        originalAmount:
          type: number
          description: Original credit amount
          format: double
          example: 5000
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Document:
      type: object
      properties:
        mimetype:
          type: string
          nullable: true
        blob:
          type: string
          nullable: true
        filename:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.GetConsumerResponse:
      type: object
      properties:
        availableCredit:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.AvailableCredit'
          nullable: true
        billingAddress:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Address'
          nullable: true
        email:
          type: string
          nullable: true
        firstName:
          type: string
          nullable: true
        id:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        mobilePhoneNumber:
          type: string
          nullable: true
        shippingAddress:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Address'
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        schemaVersion:
          type: integer
          format: int64
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.GetLegalDocsResponse:
      type: object
      properties:
        documents:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Document'
          nullable: true
        lenderId:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.Lender:
      type: object
      properties:
        id:
          type: string
          nullable: true
        name:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.LookupAccountsResponse:
      required:
      - applicationId
      type: object
      properties:
        accountsInfo:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.ConsumersV1.WebApi.Contracts.Models.AccountInfo'
          description: Consumer accounts with additional information
          nullable: true
        applicationId:
          minLength: 1
          type: string
          description: Unique identifier of the application
      additionalProperties: false
    ChargeAfter.ConsumersV1.WebApi.Contracts.Responses.PaymentPlan:
      type: object
      properties:
        creditAmount:
          type: number
          format: double
      additionalProperties: false
    ChargeAfter.Contracts.AccountStatus:
      enum:
      - None
      - New
      - NotFound
      - PreApproved
      - Approved
      - Banned
      - Declined
      - Error
      - Pending
      - PartiallyApproved
      - Frozen
      - PreDeclined
      - PendingConsumer
      type: string
    ChargeAfter.Contracts.BuyerType:
      enum:
      - Consumer
      - Organization
      type: string
    ChargeAfter.Contracts.LenderType:
      enum:
      - Unknown
      - Fortiva
      - Genesis
      - Katapult
      - Progressive
      - Synchrony
      - SynchronyRloc
      - SynchronySetPay
      - Citizens
      - PreferredLease
      - Visa
      - Aff
      - Acima
      - SplitIt
      - ZipCo
      - Milan
      - Behalf
      - LendingPoint
      - Vive
      - CoveredCare
      - Ally
      - Koalafi
      - MerchantGrowth
      - Wells_Fargo
      - Flexiti
      type: string
    ChargeAfter.Libraries.Entities.Channel:
      type: object
      properties:
        channelStr:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.Entities.ConsumerApplicationStatus:
      enum:
      - New
      - Prequalified
      - CheckoutInProgress
      - PendingConsumer
      - PendingLender
      - Approved
      - Authorized
      - Declined
      - Expired
      type: string
    ChargeAfter.Libraries.Entities.PeriodType:
      enum:
      - Day
      - Month
      - Week
      - BiWeek
      type: string
    ChargeAfter.Libraries.Entities.PosType:
      enum:
      - Kiosk
      - Retail
      - GenericMerchantDevice
      - GenericConsumerDevice
      - SelfServiceTerminal
      type: string
    ChargeAfter.Libraries.Entities.ResidenceType:
      enum:
      - OWN
      - RENT
      - OTHER
      type: string
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Account:
      required:
      - id
      - lenderId
      - lenderName
      - offers
      - status
      type: object
      properties:
        id:
          minLength: 1
          type: string
        lenderId:
          minLength: 1
          type: string
        lenderName:
          minLength: 1
          type: string
        status:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Contracts.AccountStatus'
        offers:
          type: array
          items:
            $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Offer'
        creditInfo:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.CreditInfo'
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.CreditInfo:
      type: object
      properties:
        availableCredit:
          type: number
          format: double
        maxAmount:
          type: number
          format: double
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Disclosure:
      type: object
      properties:
        type:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.DisclosureType'
        url:
          type: string
          nullable: true
        mimeType:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.DisclosureType:
      enum:
      - Link
      - Hosted
      type: string
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Eligibility:
      type: object
      properties:
        status:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.EligibilityStatus'
        ineligibilityReason:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.EligibilityStatus:
      enum:
      - Eligible
      - Ineligible
      type: string
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.FinancialProductType:
      enum:
      - LineOfCredit
      - Installments
      - LeaseToOwn
      - MerchantSelfFinancing
      type: string
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Offer:
      required:
      - amount
      - code
      - defaultAPR
      - financialProductType
      type: object
      properties:
        code:
          minLength: 1
          type: string
        financialProductType:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.FinancialProductType'
        defaultAPR:
          type: number
          format: double
        amount:
          type: number
          format: double
        promoSettings:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.PromoSettings'
          nullable: true
        metadata:
          type: object
          additionalProperties: {}
          nullable: true
        expirationDate:
          type: string
          format: date-time
          nullable: true
        checkoutMinimumAmount:
          type: number
          format: double
          nullable: true
        description:
          type: string
          nullable: true
        eligibility:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Eligibility'
          nullable: true
        tags:
          type: object
          additionalProperties:
            type: string
          nullable: true
        disclosures:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.OfferDisclosures'
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.OfferDisclosures:
      type: object
      properties:
        apply:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Disclosure'
          nullable: true
        confirm:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.Disclosure'
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.PromoSettings:
      type: object
      properties:
        isPromo:
          type: boolean
        numberOfPeriods:
          type: integer
          format: int32
          nullable: true
        periodicPayment:
          type: number
          format: double
          nullable: true
        periodType:
          allOf:
          - $ref: '#/components/schemas/ChargeAfter.Libraries.Entities.PeriodType'
          nullable: true
        apr:
          type: number
          format: double
          nullable: true
        type:
          type: string
          nullable: true
      additionalProperties: false
    ChargeAfter.Libraries.WebApi.Contracts.Responses.Offers.Models.UsabilityStatus:
      enum:
      - Unknown
      - Usable
      - AvailableLimitExceeded
      type: string
  securitySchemes:
    apiKey:
      type: apiKey
      name: Authorization
      in: header
